[package]
name = "pcap-file"
version = "0.5.0"
authors = ["François Courvoisier f.courvoisier@protonmail.com"]
description ="Read and write Pcap file"

license = "MIT"
repository = "https://github.com/courvoif/pcap_file"
readme = "README.md"
keywords = ["pcap", "file", "read", "write"]
categories = ["Encoding", "Parsing"]


[dependencies]
byteorder = "1.0.0"
error-chain = "0.10.0"