[package]
name = "pcap_rs"
version = "0.5.0"
authors = ["François Courvoisier f.courvoisier@protonmail.com"]
description ="Read and write Pcap file"
license = "MIT"

[dependencies]
byteorder = "1.0.0"
error-chain = "0.10.0"